### ISSUE TITLE
Right click is being treated as a left click in double/triple click situations

### ISSUE THREAD

**Issue by b-kelly** [StackExchange/Stacks-Editor#40]
Reported on Meta.SE [here](https://meta.stackexchange.com/a/360785/395497) and [here](https://meta.stackexchange.com/questions/360033/opt-in-alpha-test-for-a-new-stacks-editor/364583#364583)

**Describe the bug**

> After double-clicking a word to highlight it, if you quickly right-click the highlighted word to bring up the context menu, the rest of the paragraph will be highlighted, which should not be the case.
> 
> Normal behavior: (Note no new text is highlighted when context menu opens)
> 
> ![Normal text highlighting behavior](https://i.stack.imgur.com/amCdN.gif "Normal")
> 
> New behavior: (Entire paragraph is highlighted before menu opens)
> 
> ![New, broken text highlighting on context menu open](https://i.stack.imgur.com/BYSzF.gif "New")
> 
> Repro steps:
> 
> 1. Double-click word in a paragraph
> 2. Immediately right-click highlighted word

**Comment by zcoop98** [comment]
[Another answer](https://meta.stackexchange.com/questions/360033/opt-in-alpha-test-for-a-new-stacks-editor/364583#364583) was left describing the same bug with some other details:

> ### Right-clicking a word immediately after selecting it with a double-click causes the entire paragraph to be selected
> 
> It appears that the logic for selecting a paragraph with a triple-click does *not* (properly) check for which mouse button was clicked (which should be the left button only). Check the following table:
> 
> | Action | Expected behavior | Current behavior |
> | --- | --- | --- |
> | Double-click (left) + right-click | Select the word, then show the right-click menu on the selected word | Selects the *entire paragraph* and shows right-click menu. |
> | Double-click (left) + middle-click | Select the word (middle-click does nothing) | Selects the entire paragraph. |
> | Triple-click (right) | Nothing, just show the menu with every click | Selects the entire paragraph. |
> 
> Obviously, the first action is what's important as no one is likely to notice (or be bothered with) the other two but adding the right check should probably fix all three anyway.
> 
> Here's a demo:
> 
> [![Demonstrating the behavior of the first and third actions](https://i.stack.imgur.com/o3e8S.gif)](https://i.stack.imgur.com/o3e8S.gif)

**Comment by b-kelly** [comment]
Thank you @zcoop98! I updated the description on this bug to link to both

**Comment by double-beep** [comment]
That seems to be an issue with prosemirror. It was fixed in [1.18.8](https://changelogs.md/github/prosemirror/prosemirror-view/):

> Fix a bug where double-clicking with the left mouse button and then pressing another mouse button was treated as a triple click.

**Comment by b-kelly** [comment]
Thanks @double-beep, nice catch! I always read the changelogs when updating dependencies, but I must have missed this one. I can confirm that I can no longer repro the issue locally, so I'll go ahead and close this one. If we find at a later point that this is still an issue, we can reopen.
